name: sam-harmonization
channels:
  - conda-forge
  - bioconda
dependencies:
  - perl>=5.32.1
  - perl-bioperl-core
  # exonerate-sam.pl requires:
  - exonerate
  # blast-sam.pl and asn2sam.pl require:
  - blast
  # recommended additional tools
  # - mummer
  # - minimap2
  # - samtools
